# default
spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/config/spring/

  #kakao
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            redirect-uri: ${server.url}/{action}/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  #DB
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      maxFileSize: 100MB # 파일 하나의 최대 크기
      maxRequestSize: 100MB  # 한 번에 최대 업로드 가능 용량

jwt:
  token:
    secret-key: ${jwt.secret-key}
  access-token:
    expire-time: 1800000

login:
  redirect:
    url: ${login.redirect-url}

cloud:
  aws:
    s3:
      bucket:
        name: githubsalt-bucket
    credentials:
      access-key: ${aws.access-key-id}
      secret-key: ${aws.secret-access-key}
    region:
      static: ${aws.region}

aws:
  lambda:
    masking-name: ${aws.lambda.masking-name}
